apiVersion: apps/v1
kind: Deployment
metadata:
  name: volitvomat
  labels:
    app: volitvomat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volitvomat
  template:
    metadata:
      labels:
        app: volitvomat
    spec:
      containers:
        - name: volitvomat
          image: volitvomat
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: https://glas-ljudstva.si
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 100Mi
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: volitvomat
spec:
  selector:
    app: volitvomat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: volitvomat
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - volitvomat-parlamentarne-2022.djnd.si
        - volitvomat-parlamentarne-2022.danesjenovdan.si
      secretName: volitvomat-tls
  rules:
    - host: volitvomat-parlamentarne-2022.djnd.si
      http: &http_paths
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: volitvomat
                port:
                  number: 80
    - host: volitvomat-parlamentarne-2022.danesjenovdan.si
      http: *http_paths
