apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volitvomat
resources:
  - frontend.yaml
images:
  - name: volitvomat
    newName: rg.fr-par.scw.cloud/djnd/volitvomat
    newTag: '5c75ec53e00514480776586e6c2c3df051e6c7d2'