apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volitvomat
resources:
  - frontend.yaml
images:
  - name: volitvomat
    newName: rg.fr-par.scw.cloud/djnd/volitvomat
    newTag: 'd41de114719909e84a2d12f1b2054f572bd3f2d8'