apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volitvomat
resources:
  - frontend.yaml
images:
  - name: volitvomat
    newName: rg.fr-par.scw.cloud/djnd/volitvomat
    newTag: 'ad206f42939826a34c0c12641916d6b8b1bca771'