apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volitvomat-parlamentarne-2022
resources:
  - frontend.yaml
images:
  - name: volitvomat
    newName: rg.fr-par.scw.cloud/djnd/volitvomat
    newTag: '67ced2bf73a0bf57dae6897e14a308e8f276c48b'
