apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volitvomat-parlamentarne-2022
resources:
  - frontend.yaml
images:
  - name: volitvomat
    newName: rg.fr-par.scw.cloud/djnd/volitvomat
    newTag: 'ebf3d48ea5bf091aa60b1f227078badd9cd3da06'
